#!/bin/bash


WANDB__SERVICE_WAIT=300 deepspeed train.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /home/shenghao2/myLMM/huggingface/llava-onevision-qwen2-0.5b-ov/ \
    --version qwen_1_5 \
    --data_path /mnt/Datasets/LLaVA/recap/LLaVA-ReCap-558K_tag.json \
    --image_folder /mnt/Datasets/LLaVA/LLaVA-Pretrain/images \
    --vision_tower grounding_dino_mixed \
    --vision_tower_weight_path /home/shenghao2/myLMM/huggingface/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det_20231204_095047-b448804b.pth+/home/shenghao2/myLMM/huggingface/ram_plus/ram_plus_swin_large_14m.pth \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --load_ram False \
    --grounding_dino_config configs/grounding_dino_t_for_alignment.py \
    --bert_base_path /home/shenghao2/myLMM/huggingface/bert-base-uncased/ \
    --bf16 False \
    --fp16 True \
    --output_dir ./checkpoints/llava-grounding_dino_mixed-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
